### ISSUE TITLE
listpkgs.php

### ISSUE THREAD

**Issue by Wallvon** [Wallvon/MOFH-API-Docs#31]
# Return current user's available hosting plans
According to [cPanel's documentation](https://api.docs.cpanel.net/openapi/whm/operation/listpkgs/), the listpkgs endpoint does the following: "This function lists the authenticated user's available hosting plans (packages)."

## XML API:
https://panel.myownfreehost.net/xml-api/listpkgs.php
TODO. However, according to people in the [iFastNet Community Discord server](https://dsc.gg/ifastnet), the XML API endpoint is broken.
<img width="773" alt="image" src="https://github.com/Wallvon/MOFH-API-Docs/assets/42699143/4811186e-6eef-4fa1-b97d-9b872e1d3e16">

## JSON API:
https://panel.myownfreehost.net/json-api/listpkgs.php
### Call with no plans:
```json
{"package":[{"FRONTPAGE":"n","CPMOD":"x3","FEATURELIST":"default","BWLIMIT":9223372036854775807,"IP":"n","CGI":"n","MAXSUB":9999,"name":"Default","MAXSQL":999,"MAXFTP":"1","QUOTA":9223372036854775807,"MAXPARK":9999,"HASSHELL":"N","MAXADDON":9999,"MAXPOP":"10","MAXLIST":"0","LANG":"english"}]}
```

### Call with a "Test" plan:
```json
{"package":[{"FRONTPAGE":"n","CPMOD":"x3","FEATURELIST":"default","BWLIMIT":9223372036854775807,"IP":"n","CGI":"n","MAXSUB":9999,"name":"Default","MAXSQL":999,"MAXFTP":"1","QUOTA":9223372036854775807,"MAXPARK":9999,"HASSHELL":"N","MAXADDON":9999,"MAXPOP":"10","MAXLIST":"0","LANG":"english"},{"FRONTPAGE":"n","CPMOD":"x3","FEATURELIST":"default","BWLIMIT":"9223372036854775807","IP":"n","CGI":"n","MAXSUB":"9999","name":"Test","MAXSQL":"999","MAXFTP":"1","QUOTA":"9223372036854775807","MAXPARK":"9999","HASSHELL":"n","MAXADDON":"9999","MAXPOP":"10","MAXLIST":"0","LANG":"english"},{"FRONTPAGE":"n","CPMOD":"x3","FEATURELIST":"default","BWLIMIT":"9223372036854775807","IP":"n","CGI":"n","MAXSUB":"9999","name":"lve0A9SRQo1Cr7HwuqH96DngzvLxn36TYrPB9MpBiuZWE0wtplpv2ecb6lRjRWfvS2iqRMArzWMlh7czbO6YPyJucyxjSEYHC7ZPvn08hsY3ZiE1RSDvxXER1NTprFoAbgT6ZHGvqZYFFvudliUhHp4f3iZGqef6tWVNRhB2D04AwtrDP2zeocoIduHOIuPabEV332vaAdz5Guo4eSAfTlnPBlunXgIkz9XAQK7SLXE0Qrsj2sH5rJOQe8MY3MX_Test","MAXSQL":"999","MAXFTP":"1","QUOTA":"9223372036854775807","MAXPARK":"9999","HASSHELL":"n","MAXADDON":"9999","MAXPOP":"10","MAXLIST":"0","LANG":"english"}]}
```

---
Thanks to @4yx for providing the JSON API responses and for bringing up the missing endpoint.

**Comment by Wallvon** [comment]
The XML API indeed returns nothing, so I contacted iFastNet about it and I'm waiting for a reply.

**Comment by Wallvon** [comment]
> The XML API indeed returns nothing, so I contacted iFastNet about it and I'm waiting for a reply.

![image](https://github.com/Wallvon/MOFH-API-Docs/assets/42699143/c625bcfb-bafd-4b9b-ba08-6fa0228e0ec3)

iFastNet is working on resolving this now. I will update the docs when this has happened.

**Comment by chippytech** [comment]
Sorry, I don't know what a GPT-40 is.
