### ISSUE TITLE
getcname.php

### ISSUE THREAD

**Issue by Wallvon** [Wallvon/MOFH-API-Docs#33]
# Validate domain by CNAME
This endpoint allows you to add a domain using CNAME validation instead of DNS validation. It uses a POST request, which is confusing because it's called **get**cname but whatever.

> Right now it is not possible to create an account with an domain that has been verified by CNAME via the API! Its only possible to manually add that in vPanel.
\- BastelPichi

## Required parameters:
- `api_user`
- `api_key`
~~- `username`~~
- `domain_name`

## XML API:
https://panel.myownfreehost.net/xml-api/getcname.php

### Example response:
```
73081144a0525fde6ba1b0510684efcf
```

## JSON API:
https://panel.myownfreehost.net/json-api/getcname.php

### Example response:
```
73081144a0525fde6ba1b0510684efcf
```

---
Thanks to @BastelPichi for bringing up the missing endpoint.

**Comment by BastelPichi** [comment]
```curl -X POST https://panel.myownfreehost.net/xml-api/getcname.php -d 'domain_name=domain.com&username=hname_12345678&api_user=XXXXXXXXX&api_key=XXXXXXXXXX' -u XXXXXXX:XXXXXXXXXX```
Returns: `73081144a0525fde6ba1b0510684efcf`

Using the json API vs the XML API makes no difference.
The username is irrelevant and doesnt matter. (they probably left it in by mistake), however its still good practice to send the actual username.

By creating an CNAME record from HASH_VALUE.domain.com to ns1.byet.org the domain can be added to cPanel without changing nameservers.

Right now it is not possible to create an account with an domain that has been verified by CNAME via the API! Its only possible to manually add that in vPanel.

**Comment by BastelPichi** [comment]
![IMG_20231213_091633.jpg](https://github.com/Wallvon/MOFH-API-Docs/assets/63782569/f456ee4d-18af-4d92-9250-15ae2a1b19aa)

You shouldn't need the username now anymore.

**Comment by Wallvon** [comment]
> ![IMG_20231213_091633.jpg](https://private-user-images.githubusercontent.com/63782569/290121941-f456ee4d-18af-4d92-9250-15ae2a1b19aa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0Njc1NzAsIm5iZiI6MTcwMjQ2NzI3MCwicGF0aCI6Ii82Mzc4MjU2OS8yOTAxMjE5NDEtZjQ1NmVlNGQtMThhZi00ZDkyLTkyNTAtMTVhZTJhMWIxOWFhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDExMzQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZWY3ZGYwN2U4MDk1MDgxYmUwZDM3NDA5NTM2ZGVmNGEyZDdjZWMyZGQyNTQ2ZDRlMmE4NDIzNzJhZjgxYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A1zWfKjCkW5saklE4CJky5gZTrDyItIcrltpn2A7WlA)
> 
> You shouldn't need the username now anymore.

Seems like they've broken the endpoint with that change since now I only get `ERROR :The API key or API username entered is not valid. .`

It also seems like they changed back to query parameters instead of multipart form, just like all other endpoints.

**Comment by BastelPichi** [comment]
> > ![IMG_20231213_091633.jpg](https://private-user-images.githubusercontent.com/63782569/290121941-f456ee4d-18af-4d92-9250-15ae2a1b19aa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0Njc1NzAsIm5iZiI6MTcwMjQ2NzI3MCwicGF0aCI6Ii82Mzc4MjU2OS8yOTAxMjE5NDEtZjQ1NmVlNGQtMThhZi00ZDkyLTkyNTAtMTVhZTJhMWIxOWFhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDExMzQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZWY3ZGYwN2U4MDk1MDgxYmUwZDM3NDA5NTM2ZGVmNGEyZDdjZWMyZGQyNTQ2ZDRlMmE4NDIzNzJhZjgxYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A1zWfKjCkW5saklE4CJky5gZTrDyItIcrltpn2A7WlA)
> > 
> > You shouldn't need the username now anymore.
> 
> Seems like they've broken the endpoint with that change since now I only get `ERROR :The API key or API username entered is not valid. .`
> 
> It also seems like they changed back to query parameters instead of multipart form, just like all other endpoints.

The other endpoints do use body data (at least thats how your docs specify it and that way it also works). What happens if you use body data?

**Comment by Wallvon** [comment]
> The other endpoints do use body data (at least thats how your docs specify it and that way it also works). What happens if you use body data?

I get the same error then it seems.

**Comment by BastelPichi** [comment]
> > The other endpoints do use body data (at least thats how your docs specify it and that way it also works). What happens if you use body data?
> 
> I get the same error then it seems.

Thats interesting, ill look into this later.

**Comment by Wallvon** [comment]
I've contacted iFastNet about this ^
