### ISSUE TITLE
Remove/edit "account suspension" from ticket system callbacks section

### ISSUE THREAD

**Issue by Wallvon** [Wallvon/MOFH-API-Docs#36]
Currently, there is a section with "account suspension" in the ticket system section of the callbacks page:
<img width="775" alt="image" src="https://github.com/Wallvon/MOFH-API-Docs/assets/42699143/9a5f0ab9-f944-4c0e-b095-23cd9b417b46">

This seems to have happened in the callback update, #22, and I don't know what it is supposed to say there. Does anyone have an idea?

CC: @greenreader9

**Comment by greenreader9** [comment]
Referencing #38 @Wallvon
